version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: khilkov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      
      - run:
          TAG=0.1$CIRCLE_BUILD_NUM
          docker build -t VictoriaHilko/circleci-demo-docker:$TAG .
          docker login -u VictoriaHilko - p $DOCKERHUB_PASSWORD
          docker push khilkov/circleci-demo-docker:$TAG
