version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: khilkov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      
      - run:
          
          docker build -t khilkov/circleci-demo-docker
          docker login -u khilkov -p $DOCKERHUB_PASSWORD
          docker push khilkov/circleci-demo-docker
